import { Student } from './types';

export const initialStudents: Student[] = [
  {
    id: 1,
    name: "Ali Khan",
    department: "Computer Science",
    semester: 6,
    email: "ali@example.com",
    phone: "03001234567",
    cgpa: 3.5,
    skills: ["React", "JavaScript", "Bootstrap"],
    image: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80",
    status: "Active",
    motto: "Code is like humor. When you have to explain it, it’s bad.",
    bio: "Ali is a passionate web developer focused on front-end architectures. He spends his free time contributing to open-source libraries and experimenting with custom animation scripts in React and WebGL.",
    projectTitle: "OmniChannel State Distributer",
    completedCredits: 96
  },
  {
    id: 2,
    name: "Sara Ahmed",
    department: "Software Engineering",
    semester: 4,
    email: "sara@example.com",
    phone: "03111234567",
    cgpa: 3.8,
    skills: ["HTML", "CSS", "React"],
    image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    status: "Active",
    motto: "Simplicity is the soul of modern design.",
    bio: "Sara specializes in UX research and interactive design systems. She bridges the gap between sophisticated human workflows and elegant web UI components with high-fidelity performance metrics.",
    projectTitle: "Fluidic User Interaction Engine",
    completedCredits: 64
  },
  {
    id: 3,
    name: "Daniyal Shah",
    department: "Data Science",
    semester: 7,
    email: "daniyal@example.com",
    phone: "03211234567",
    cgpa: 3.9,
    skills: ["Python", "SQL", "Pandas", "Scikit-Learn"],
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    status: "Inactive",
    motto: "In God we trust, all others must bring data.",
    bio: "Daniyal is a statistician building predictive analysis pipelines. He studies high-dimensional tabular clusters, focusing on machine learning automation models and statistical anomalies in large datasets.",
    projectTitle: "Predictive Cluster Classifier",
    completedCredits: 112
  },
  {
    id: 4,
    name: "Zainab Fatima",
    department: "Cyber Security",
    semester: 5,
    email: "zainab@example.com",
    phone: "03331234567",
    cgpa: 3.2,
    skills: ["Linux", "Wireshark", "Network Security"],
    image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    status: "Active",
    motto: "Security is not a product, but a constant process.",
    bio: "Zainab concentrates on penetration testing, threat mapping, and ethical hacking exercises. She loves configuring secure host interfaces and tracking firewall integrity logs.",
    projectTitle: "Dynamic Threat Ingress Guard",
    completedCredits: 80
  },
  {
    id: 5,
    name: "Humza Lodhi",
    department: "Artificial Intelligence",
    semester: 8,
    email: "humza@example.com",
    phone: "03451234567",
    cgpa: 3.7,
    skills: ["TensorFlow", "PyTorch", "Python", "Deep Learning"],
    image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    status: "Active",
    motto: "Automating tomorrow, deciphering today.",
    bio: "Humza is writing neural network algorithms for computer vision tasks or natural language synthesis models. He is also passionate about robotic cognitive control loops.",
    projectTitle: "HyperSpectral Image Segmenter",
    completedCredits: 128
  },
  {
    id: 6,
    name: "Ayesha Malik",
    department: "Information Technology",
    semester: 3,
    email: "ayesha@example.com",
    phone: "03551234567",
    cgpa: 3.4,
    skills: ["Java", "SQL", "PHP", "Bootstrap"],
    image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    status: "Inactive",
    motto: "Technology empowers dreams with execution.",
    bio: "Ayesha is an ambitious full-stack builder who enjoys database normalization, hosting server endpoints, and building modular client layouts with responsive grid configurations.",
    projectTitle: "Distributed Schema Hub Platform",
    completedCredits: 48
  }
];
